// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mYPMS.Data;

#nullable disable

namespace mYPMS.Migrations
{
    [DbContext(typeof(mYPMSContext))]
    partial class mYPMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("mYPMS.Models.tGate", b =>
                {
                    b.Property<Guid>("xId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xBarrierInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xBarrierOutUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("xDirection")
                        .HasColumnType("int");

                    b.Property<string>("xImageInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xImageOutUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("xParkingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xVideoInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xVideoOutUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("xId");

                    b.HasIndex("xParkingId");

                    b.ToTable("tGates");
                });

            modelBuilder.Entity("mYPMS.Models.tParking", b =>
                {
                    b.Property<Guid>("xId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("xCapacity")
                        .HasColumnType("int");

                    b.Property<string>("xCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("xContractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xCordination")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("xDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("xPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("xReservedCapacity")
                        .HasColumnType("int");

                    b.Property<string>("xSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("xStatusCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("xTariffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("xId");

                    b.HasIndex("xTariffId");

                    b.ToTable("tParkings");
                });

            modelBuilder.Entity("mYPMS.Models.tPaymentMethod", b =>
                {
                    b.Property<Guid>("xId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xPaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("xId");

                    b.ToTable("tPaymentMethods");
                });

            modelBuilder.Entity("mYPMS.Models.tSetting", b =>
                {
                    b.Property<Guid>("xId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("xRelationship")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("xId");

                    b.ToTable("tSettings");
                });

            modelBuilder.Entity("mYPMS.Models.tTagGroup", b =>
                {
                    b.Property<Guid>("xId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("xTariffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("xId");

                    b.HasIndex("xTariffId");

                    b.ToTable("tTagGroup");
                });

            modelBuilder.Entity("mYPMS.Models.tTagList", b =>
                {
                    b.Property<string>("xId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("xComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("xExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("xTagGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("xId");

                    b.HasIndex("xTagGroupId");

                    b.ToTable("tTagList");
                });

            modelBuilder.Entity("mYPMS.Models.tTariff", b =>
                {
                    b.Property<Guid>("xId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("xDayHourPrice")
                        .HasColumnType("int");

                    b.Property<string>("xDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("xEntryPrice")
                        .HasColumnType("int");

                    b.Property<int?>("xNightEndHour")
                        .HasColumnType("int");

                    b.Property<int?>("xNightHourPrice")
                        .HasColumnType("int");

                    b.Property<int?>("xNightStartHour")
                        .HasColumnType("int");

                    b.Property<string>("xTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("xWholeDayPrice")
                        .HasColumnType("int");

                    b.HasKey("xId");

                    b.ToTable("tTariffs");
                });

            modelBuilder.Entity("mYPMS.Models.tTraffic", b =>
                {
                    b.Property<Guid>("xId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("xDepartureDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("xDepartureGateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("xDepartureOperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("xEntryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("xEntryGateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("xEntryOperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xLicencePlateEn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("xLicencePlateEx")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("xPaid")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("xPaidMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("xParkingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("xStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("xTagId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("xTariffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("xId");

                    b.HasIndex("xDepartureGateId");

                    b.HasIndex("xDepartureOperatorId");

                    b.HasIndex("xEntryGateId");

                    b.HasIndex("xEntryOperatorId");

                    b.HasIndex("xPaidMethodId");

                    b.HasIndex("xParkingId");

                    b.HasIndex("xTariffId");

                    b.ToTable("tTraffics");
                });

            modelBuilder.Entity("mYPMS.Models.tUser", b =>
                {
                    b.Property<Guid>("xId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("xDecription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xMobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("xName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("xPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("xPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("xRules")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("xUsername")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("xId");

                    b.ToTable("tUsers");
                });

            modelBuilder.Entity("mYPMS.Models.vParked", b =>
                {
                    b.Property<DateTime>("xEnterDateTime")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("xEnterOperatorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("xExitDateTime")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("xExitOperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("xGate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("xId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xLicencePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("xParkingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("xPayment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("xPaymentMethod")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("xProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("xStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("xTagId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("vParkeds");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mYPMS.Models.tGate", b =>
                {
                    b.HasOne("mYPMS.Models.tParking", "xParking")
                        .WithMany("xGates")
                        .HasForeignKey("xParkingId");

                    b.Navigation("xParking");
                });

            modelBuilder.Entity("mYPMS.Models.tParking", b =>
                {
                    b.HasOne("mYPMS.Models.tTariff", "xTariff")
                        .WithMany()
                        .HasForeignKey("xTariffId");

                    b.Navigation("xTariff");
                });

            modelBuilder.Entity("mYPMS.Models.tTagGroup", b =>
                {
                    b.HasOne("mYPMS.Models.tTariff", "xTariff")
                        .WithMany()
                        .HasForeignKey("xTariffId");

                    b.Navigation("xTariff");
                });

            modelBuilder.Entity("mYPMS.Models.tTagList", b =>
                {
                    b.HasOne("mYPMS.Models.tTagGroup", "xTagGroup")
                        .WithMany("xTagList")
                        .HasForeignKey("xTagGroupId");

                    b.Navigation("xTagGroup");
                });

            modelBuilder.Entity("mYPMS.Models.tTraffic", b =>
                {
                    b.HasOne("mYPMS.Models.tGate", "xDepartureGate")
                        .WithMany()
                        .HasForeignKey("xDepartureGateId");

                    b.HasOne("mYPMS.Models.tUser", "xDepartureOperator")
                        .WithMany()
                        .HasForeignKey("xDepartureOperatorId");

                    b.HasOne("mYPMS.Models.tGate", "xEntryGate")
                        .WithMany()
                        .HasForeignKey("xEntryGateId");

                    b.HasOne("mYPMS.Models.tUser", "xEntryOperator")
                        .WithMany()
                        .HasForeignKey("xEntryOperatorId");

                    b.HasOne("mYPMS.Models.tPaymentMethod", "xPaidMethod")
                        .WithMany()
                        .HasForeignKey("xPaidMethodId");

                    b.HasOne("mYPMS.Models.tParking", "xParking")
                        .WithMany()
                        .HasForeignKey("xParkingId");

                    b.HasOne("mYPMS.Models.tTariff", "xTariff")
                        .WithMany()
                        .HasForeignKey("xTariffId");

                    b.Navigation("xDepartureGate");

                    b.Navigation("xDepartureOperator");

                    b.Navigation("xEntryGate");

                    b.Navigation("xEntryOperator");

                    b.Navigation("xPaidMethod");

                    b.Navigation("xParking");

                    b.Navigation("xTariff");
                });

            modelBuilder.Entity("mYPMS.Models.tParking", b =>
                {
                    b.Navigation("xGates");
                });

            modelBuilder.Entity("mYPMS.Models.tTagGroup", b =>
                {
                    b.Navigation("xTagList");
                });
#pragma warning restore 612, 618
        }
    }
}
