// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using mYPMS.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace mYPMS.Data
{
    public partial interface ImYPMSContextProcedures
    {
        Task<int> GetFreeLotsAsync(Guid? ParkingId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SumReportResult>> SumReportAsync(DateTime? start, DateTime? end, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
