// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mYPMS.Models
{
    [Keyless]
    public partial class vParked
    {
        public Guid xId { get; set; }
        [Required]
        [StringLength(20)]
        public string xTagId { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime xEnterDateTime { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? xExitDateTime { get; set; }
        [Required]
        [StringLength(50)]
        public string xEnterOperatorName { get; set; }
        [StringLength(50)]
        public string xExitOperatorName { get; set; }
        [StringLength(20)]
        public string xLicencePlate { get; set; }
        public string xProperties { get; set; }
        public int? xStatusCode { get; set; }
        [StringLength(50)]
        public string xGate { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? xPayment { get; set; }
        public Guid? xPaymentMethod { get; set; }
        public Guid? xParkingId { get; set; }
    }
}